[package]
authors = ["Gulshan Dhingra <gdgulshan.007@gmail.com>"]
description = "MaxmindDB GeoLocation"
edition = "2024"
homepage = "https://github.com/DGulshan/maxmind-geoip-rs"
license = "MIT"
name = "maxmind-geoip"
readme = "README.md"
repository = "https://github.com/DGulshan/maxmind-geoip-rs"
version = "0.2.0"

[dependencies]
flate2 = "1"
maxminddb = "0.27.3"
reqwest = "0.13.2"
tar = "0.4"
tokio = { version = "1", features = ["sync"] }
